In [1]:
import numpy as np

def matrix_addition(matrix_a, matrix_b):
    return np.add(matrix_a, matrix_b)

def matrix_subtraction(matrix_a, matrix_b):
    return np.subtract(matrix_a, matrix_b)

def matrix_multiplication(matrix_a, matrix_b):
    return np.dot(matrix_a, matrix_b)

def matrix_inversion(matrix):
    try:
        return np.linalg.inv(matrix)
    except np.linalg.LinAlgError:
        print("Matrix is not invertible.")

def matrix_transpose(matrix):
    return np.transpose(matrix)

# Sample matrices for testing
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print("Matrix1:",matrix1,sep="\n")
print("Matrix2:",matrix2,sep="\n")

print("Matrix Addition:")
print(matrix_addition(matrix1, matrix2))

print("\nMatrix Subtraction:")
print(matrix_subtraction(matrix1, matrix2))

print("\nMatrix Multiplication:")
print(matrix_multiplication(matrix1, matrix2))

print("\nMatrix Inversion:")
print(matrix_inversion(matrix1))

print("\nMatrix Transpose:")
print(matrix_transpose(matrix1))


Matrix1:
[[1 2]
 [3 4]]
Matrix2:
[[5 6]
 [7 8]]
Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Subtraction:
[[-4 -4]
 [-4 -4]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Matrix Inversion:
[[-2.   1. ]
 [ 1.5 -0.5]]

Matrix Transpose:
[[1 3]
 [2 4]]
